name: Dependency Cache Test

on:
  workflow_dispatch:  # manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Prime cache
        id: prime-cache-b5aa670
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-b5aa670
          restore-keys: |
            cache-b5aa670

      - name: Show cache result
        run: |
          if [ "${{ steps.prime-cache-b5aa670.outputs.cache-hit }}" == 'true' ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
